getSteamData: true
id: alchemy_factory
isSteamGame: true
name: Alchemy Factory
processEndCommand: null
run: path/to/exe
saveInGameFolder: true
savePath: path/to/savefolder
uploadEndCommand: null
url: 192.168.1.200:6769
user: alice
